#---------------------------
# スクリーニング機能の設定
# (高確率型)
#---------------------------
[SCREENING]

# 売買区分(0:買い, 1:売り, 2:両方) ==>「1:売り, 2:両方」は買いポジション最大保持期間が0の場合のみ有効
SCR_SELLBUY = 2

# 実行モード(0:テスト用、1:本番用)
SCR_EXEC_MODE = 1

#/// 判定処理の有効(1)/無効(0) 設定 ///
# ローソク足判定
SCR_JDG_CAND = 0

# 指標銘柄判定
SCR_JDG_IND = 0

# 移動平均線判定
SCR_JDG_MOV = 1

# 移動平均パーフェクトオーダー判定(移動平均線判定有効時のみ設定有効)
SCR_JDG_MOV_PFCT = 1

# 移動平均パーフェクトオーダー判定(移動平均線判定有効時のみ設定有効)
SCR_JDG_MOV_PUSH = 1

# RSI判定
SCR_JDG_RSI = 0

# ボリンジャー判定
SCR_JDG_BOLIN = 0

# MACD判定
SCR_JDG_MACD = 0

# ブレイクアウト判定
SCR_JDG_BRK = 0

# 髭判定
SCR_JDG_BERD = 0

#/// 各判定に使用するパラメータ ///
# 過去何日前までの株価データを使用するか
# 注：(最古)過去4279日とする。 (2010年1月4日開始) これ以前はnullの混ざる銘柄が多い
SCR_PAST_PERIOD = 150

# 買いポジション最大保持期間
SCR_SELL_PERIOD = 5

# ブレイクアウト判定期間に使用する値
SCR_BREAK_PERIOD = 7

# ブレイクアウトオフセット。上限を何%超えたか。(1/100で計算)
SCR_BREAK_OFSET = 0.01

# MACDとシグナルの開き
SCR_MACD_OFSET = 5

# 買いシグナルに使用する長期移動平均線(上昇時に買)
SCR_LINEAVE = 75

# 買シグナルを出す上限RSI
SCR_RSI_MAX = 100

# RSIの下限値。scr_rsi_perが無効（-1）の時に採用する。
SCR_RSI_BORDER = 55

# RSIの下限を全体の%で決める時の値。-1の時はrsi_borderを使用
SCR_RSI_PER = -1

# RSIの値を何日まで遡ってみるか
SCR_RSI_PERIOD = 14

# 指標銘柄コード
SCR_IND_CODE = 1321

#---------------------------
# 集計結果
#---------------------------
[SHUUKEI]
# 調査用集計ファイル保存パス
PATH_SHUUKEI = ..\..\output\analys\

# 本番用集計ファイル保存パス
PATH_HONBAN = ..\..\output\honban\

#---------------------------
# 登録データ関連
#---------------------------
[ENTRY]
# PFデータ読み込み先パス
PATH_CODESET = ..\..\Input\PF\

#---------------------------
# データベース関連
#---------------------------
[DATABASE]
# DBパス
#PATH_DB = L:\KabuRadar\DB\KabuRadar.db
PATH_DB = ..\..\DB\KabuRadar.db

#---------------------------
# カブコムAPI用の設定
#---------------------------
[KABUSAPI]
# ログインパスワード
#API_PASSWD = abc12345
API_PASSWD = morino12345

# トレードパスワード
TRD_PASSWD = tanto6570


