[SHUUKEI]
#PATH = E:\KabuRadar\analys\
# 調査用集計ファイル保存パス
PATH_SHUUKEI = ..\..\output\analys\
# 本番用集計ファイル保存パス
PATH_HONBAN = ..\..\output\honban\
#PATH = ..\analys\	
#PATH = C:\MorinoFolder\Python\KabuRadar\過去分析\analys_break期間調査20-25\24\

[ENTRY]
# PFデータ読み込み先パス
PATH_CODESET = ..\Input\PF\

#カブコムAPI用の設定
[KABUSAPI]
# ログインパスワード
#API_PASSWD = abc12345
API_PASSWD = morino12345
# トレードパスワード
TRD_PASSWD = tanto6570

#データベース
[DATABASE]
# DBパス
PATH_DB = L:\KabuRadar\DB\KabuRadar.db
#PATH_DB = ..\..\DB\KabuRadar.db

